debug:
    # Forwards VarDumper Data clones to TechnoType.php centralized server allowing to inspect dumps on CLI or in your browser.
    # See the "server:dump" command to start TechnoType.php new server.
    dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"
